steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pacific-ethos-388512/sample_docker_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pacific-ethos-388512/sample_docker_app']